id: AF323580C
title: Prayer for the Long Life of Alak Zenkar Rinpoche
type: translation
pechas:
- I06FF5C73
- ID88F880D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:34.996873
  last_modified_at: 2023-01-04 11:39:34.996885
  collections:
  - Do Dasel Wangmo Series
  - Works of Tibetan Masters
alignment_to_base:
  I06FF5C73/9047: D4DA
  ID88F880D/2D39: D4DA
